[app]
title = WingPay Sentinel
package.name = wingpay_sentinel
package.domain = com.inversioneswing.sentinel
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 36.0
requirements = python3,kivy,plyer,android
orientation = portrait
osx.python_version = 3
osx.kivy_version = 1.9.1
fullscreen = 0
android.permissions = INTERNET, VIBRATE, WAKE_LOCK, RECEIVE_BOOT_COMPLETED, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE, POST_NOTIFICATIONS
android.api = 33
android.minapi = 21
android.sdk = 33
android.ndk = 25b
android.archs = arm64-v8a
android.allow_backup = True
